COSE Signed API
a-sit-plus/signum pull request #194
Opened 2024-11-13 10:34 UTC by nodh

Adds a type parameter to `CoseSigned`. While not as thorough as for `JwsSigned`, it's still worth it to provide some form of guidance to clients as which payload to expect.

2024-11-15 09:18 UTC, JesusMcCloud requested changes
Why does this behave differently from JwsSigned, that has the typed payload as property? should not the seriializer handle conversion from/to bytestringwrapper?

2024-11-15 09:18 UTC, JesusMcCloud commented on indispensable-cosef/src/commonMain/kotlin/at/asitplus/signum/indispensable/cosef/CoseSigned.kt
> +    fun getTypedPayload(deserializationStrategy: DeserializationStrategy<P>): KmmResult<P?> = catching {
This should be lazy and a test that is not already based on a bytearray would be nice

2024-11-15 09:22 UTC, JesusMcCloud commented
> Why does this behave differently from JwsSigned, that has the typed payload as property? should not the seriializer handle conversion from/to bytestringwrapper?

In VCK, there's bytestringwrapper all over the place, i think we can do away with it and add this wrapping logic into the serializer, while we're at it

2024-11-15 10:33 UTC, JesusMcCloud commented
@n0900 can this be made more convenient: as in: directly pass the typed payload to the constructor and have the serializer handle the byte string wrapping? I know it's different from your serialization foo, because it can by any type, but still…

2024-11-15 10:34 UTC, nodh commented
Best I can do with my knowledge of kotlinx serialization ... `CoseSignedSerializer` can't handle the payload directly, because it doesn't know about the type of the payload, since it's referenced by annotation on `CoseSigned`. In contrast, `JwsSigned` itself is not annotated with `@Serializable`, so it is easier there. I'm happy for any suggestions on how to solve the shortcomings.

2024-11-21 10:39 UTC, JesusMcCloud approved these changes

2024-11-25 07:47 UTC, merged